name: fatura_yeni
description: "Akıllı fatura tanıma ve yönetim uygulaması."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1 
  
  # API İstekleri
  http: ^1.2.1
  http_parser: ^4.0.2
  
  # Vektörel İkonlar
  flutter_svg: ^2.0.10+1
  
  # Özel Fontlar
  google_fonts: ^6.2.1
  
  # iOS Stili İkonlar
  cupertino_icons: ^1.0.6
  
  # Çoklu Dil Desteği (i18n)
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # Özel UI Bileşenleri
  intl_phone_field: ^3.2.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.3
  intl_phone_number_input: ^0.7.4
  flutter_localization: ^0.2.0
  image_picker: ^1.1.2

  # Firebase Entegrasyonu
  firebase_core: ^3.1.1
  firebase_auth: ^5.7.0

  # Güvenli Depolama
  flutter_secure_storage: ^9.2.2

  # Dosya ve Resim Seçimi
  file_picker: ^8.0.6
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

# Flutter'a özel yapılandırmalar bu tek bölüm altında toplanmalıdır.
flutter:
  uses-material-design: true
  generate: true # Çoklu dil desteği için kod üretimi

  # Uygulama varlıkları (resim, json vb.)
  assets:
    - assets/