// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvkeHjd24OseCa5el4X0H_sLXA4lrrX7Q',
    appId: '1:251889727921:web:078e94db56dd533febe590',
    messagingSenderId: '251889727921',
    projectId: 'faturatanimauygulamasi',
    authDomain: 'faturatanimauygulamasi.firebaseapp.com',
    storageBucket: 'faturatanimauygulamasi.firebasestorage.app',
    measurementId: 'G-JR1H899CZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqOojiqkl9SIAoHE5tN2ld82OCFgoM2U',
    appId: '1:251889727921:android:d1bbbaaf5b28f9fcebe590',
    messagingSenderId: '251889727921',
    projectId: 'faturatanimauygulamasi',
    storageBucket: 'faturatanimauygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBp91I8D2psjE46vHr3jR25zy5PS6XZuk',
    appId: '1:251889727921:ios:4af0a05a49218e56ebe590',
    messagingSenderId: '251889727921',
    projectId: 'faturatanimauygulamasi',
    storageBucket: 'faturatanimauygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.faturaYeni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBp91I8D2psjE46vHr3jR25zy5PS6XZuk',
    appId: '1:251889727921:ios:4af0a05a49218e56ebe590',
    messagingSenderId: '251889727921',
    projectId: 'faturatanimauygulamasi',
    storageBucket: 'faturatanimauygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.faturaYeni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvkeHjd24OseCa5el4X0H_sLXA4lrrX7Q',
    appId: '1:251889727921:web:c874642c1e895692ebe590',
    messagingSenderId: '251889727921',
    projectId: 'faturatanimauygulamasi',
    authDomain: 'faturatanimauygulamasi.firebaseapp.com',
    storageBucket: 'faturatanimauygulamasi.firebasestorage.app',
    measurementId: 'G-CJLD3G5BDP',
  );
}
