// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGB_uUFYJL2yQnY8x7G8_-Ik8wO6Q5QQ',
    appId: '1:313660975832:web:2c97559b989e7eb4ca45ad',
    messagingSenderId: '313660975832',
    projectId: 'yepyenifa',
    authDomain: 'yepyenifa.firebaseapp.com',
    storageBucket: 'yepyenifa.firebasestorage.app',
    measurementId: 'G-THTLSFQSMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVd9B-3pk6txxGOqnOjcI16mq_ucIG_fA',
    appId: '1:313660975832:android:184502d4f45cafb7ca45ad',
    messagingSenderId: '313660975832',
    projectId: 'yepyenifa',
    storageBucket: 'yepyenifa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVVPKHVSzR-l6CGhwqtTqijY7AxJMmJWY',
    appId: '1:313660975832:ios:d1162ed0186f6542ca45ad',
    messagingSenderId: '313660975832',
    projectId: 'yepyenifa',
    storageBucket: 'yepyenifa.firebasestorage.app',
    iosBundleId: 'com.example.faturaYeni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVVPKHVSzR-l6CGhwqtTqijY7AxJMmJWY',
    appId: '1:313660975832:ios:d1162ed0186f6542ca45ad',
    messagingSenderId: '313660975832',
    projectId: 'yepyenifa',
    storageBucket: 'yepyenifa.firebasestorage.app',
    iosBundleId: 'com.example.faturaYeni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkGB_uUFYJL2yQnY8x7G8_-Ik8wO6Q5QQ',
    appId: '1:313660975832:web:b99e357bd9949ad9ca45ad',
    messagingSenderId: '313660975832',
    projectId: 'yepyenifa',
    authDomain: 'yepyenifa.firebaseapp.com',
    storageBucket: 'yepyenifa.firebasestorage.app',
    measurementId: 'G-Y7X3K0DJ35',
  );

}